# Generated by Django 4.1.3 on 2022-11-29 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name=' نام ارز')),
                ('brand', models.CharField(max_length=100, null=True, verbose_name=' نماد ارز')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='MainTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=' نام ارز')),
                ('brand', models.CharField(max_length=100, null=True, verbose_name=' نماد ارز')),
                ('bcurrency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buycurrency', to='main.currency')),
                ('scurrency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sellcurrency', to='main.currency')),
            ],
            options={
                'verbose_name': 'MainTrade',
                'verbose_name_plural': 'MainTrades',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('amount', models.FloatField()),
                ('price', models.FloatField()),
                ('start', models.FloatField(null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellorders', to='main.maintrade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintradesellorders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
