# Generated by Django 4.1.3 on 2022-12-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='leverage',
            field=models.IntegerField(default=0),
        ),
    ]
