# Generated by Django 4.1.3 on 2023-01-07 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_pinver'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='closed',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='funding',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='ClosedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=100)),
                ('type', models.IntegerField()),
                ('amount', models.FloatField()),
                ('price', models.FloatField()),
                ('start', models.FloatField(null=True)),
                ('leverage', models.IntegerField(default=0)),
                ('funding', models.FloatField(null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='his', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
