# Generated by Django 4.1.3 on 2023-01-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_order_closed_order_funding_closedorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='closedorder',
            old_name='start',
            new_name='startprice',
        ),
        migrations.AddField(
            model_name='order',
            name='startamount',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
    ]
