# Generated by Django 4.1.3 on 2023-01-07 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_order_startamount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='startamount',
        ),
    ]
