# Generated by Django 4.1.3 on 2023-01-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_order_startamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='startamount',
            field=models.FloatField(null=True),
        ),
    ]
