# Generated by Django 4.1.3 on 2023-01-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_order_startamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='closedorder',
            name='fee',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='closedorder',
            name='pnl',
            field=models.FloatField(null=True),
        ),
    ]
