# Generated by Django 4.1.3 on 2023-01-07 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_closedorder_fee_closedorder_pnl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closedorder',
            name='startprice',
        ),
    ]
