# Generated by Django 4.1.3 on 2023-01-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_closedorder_startprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='closedorder',
            name='startprice',
            field=models.FloatField(null=True),
        ),
    ]
